# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas de Paula
email: lucasdepaula@poli.ufrj.br
description: > # this means to ignore newlines until "baseurl:"
  Lucas de Paula é estudante do 6º período de Engenharia de Computação e Informação na Universidade Federal do Rio e Janeiro.
  Este blog contém algumas das minhas aventuras como estudante, programador, gamer, e tudo mais!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucasnaweb.com.br" # the base hostname & protocol for your site
twitter_username: olucasnaweb
github_username:  lucasdepaula
image_folder: '/images'
# Build settings
markdown: kramdown
